### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by miron0xff** [kintama48/array_utils#1]
Hi! I faced an error while using this library. 
In last block of code you have mixed tabs and spaces so Python throws an error:

```
File "/.../venv/lib/python3.9/site-packages/array_utils/code.py", line 22
    if endpoint:
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by kintama48** [comment]
Hi Aleksandr!

Thanks for bringing this error to my attention. I made this library for a college project; I didn't think that someone would actually use it. Anyways, the issue is fixed now. 

Best regards,
Abdullah Baig

**Comment by miron0xff** [comment]
I've found your lib as a dependency in a project I'm in =)
